"""Playback for the bundled tab-attention notification sounds.

The sounds in ``data/sounds`` are generated by ``tools/generate_notification_sounds.py``
— procedural synthesis, no third-party audio — so shipping them carries no
licence obligations.

Playback goes through GSound (libcanberra), which is what the freedesktop stack
already uses for event sounds: it respects the user's sound settings and needs
no GStreamer pipeline. GSound is optional at runtime; without it every play call
is a silent no-op rather than an error, since a terminal must never fail to open
because an audio library is missing.
"""

from pathlib import Path
from typing import Dict, List, Optional

from .logger import get_logger

_logger = get_logger("ashyterm.utils.sound")

SOUNDS_DIR = Path(__file__).parent.parent / "data" / "sounds"

# Ordered for the preferences dropdown: shortest and driest first, longest and
# most melodic last, so scrolling the list sweeps a spectrum instead of jumping
# around. Labels are translated at the call site.
NOTIFICATION_SOUNDS: List[str] = [
    "pop",
    "blip",
    "double",
    "pluck",
    "rise",
    "settle",
    "success",
    "chime",
    "bell",
    "soft",
]

# Value stored in settings when the user wants no sound at all.
SOUND_NONE = "none"

_context = None
_context_failed = False


def _get_context():
    """Lazily build the shared GSound context, or None when unavailable."""
    global _context, _context_failed
    if _context is not None or _context_failed:
        return _context

    try:
        import gi

        gi.require_version("GSound", "1.0")
        from gi.repository import GSound

        context = GSound.Context()
        context.init()
        _context = context
    except Exception as exc:
        _context_failed = True
        _logger.info(f"Notification sounds unavailable (GSound): {exc}")
    return _context


def sound_path(name: str) -> Optional[Path]:
    """Absolute path of a bundled sound, or None if the name is not shipped."""
    if not name or name == SOUND_NONE or name not in NOTIFICATION_SOUNDS:
        return None
    path = SOUNDS_DIR / f"{name}.oga"
    return path if path.exists() else None


def play_notification_sound(name: str) -> bool:
    """Play a bundled sound by name. True when playback was handed off.

    Never raises: a missing sound, an unreadable file or an unusable audio
    backend all resolve to False.
    """
    path = sound_path(name)
    if path is None:
        return False

    context = _get_context()
    if context is None:
        return False

    try:
        import gi

        gi.require_version("GSound", "1.0")
        from gi.repository import GSound

        attrs: Dict[str, str] = {
            GSound.ATTR_EVENT_ID: f"ashyterm-{name}",
            GSound.ATTR_MEDIA_FILENAME: str(path),
            GSound.ATTR_MEDIA_ROLE: "event",
        }
        context.play_simple(attrs)
        return True
    except Exception as exc:
        _logger.warning(f"Failed to play notification sound '{name}': {exc}")
        return False
