"""Quick prompt list for AI chat conversations."""

from __future__ import annotations

import random

from ....utils.translation_utils import _


# Extended list of quick prompts (200+ items) - random selection shown per new conversation
ALL_QUICK_PROMPTS = [
    # Basic Terminal Help
    ("📁", _("How do I navigate directories?")),
    ("🔍", _("How do I find files by name?")),
    ("📝", _("How do I edit files in terminal?")),
    ("📊", _("How do I view disk usage?")),
    ("🔐", _("How do I change file permissions?")),
    ("📦", _("How do I compress files?")),
    ("🌐", _("How do I check my IP address?")),
    ("⚙️", _("How do I view running processes?")),
    ("💾", _("How do I check memory usage?")),
    ("🔄", _("How do I restart a service?")),
    # Git Commands
    ("🌿", _("How do I create a new branch?")),
    ("🔀", _("How do I merge branches?")),
    ("📤", _("How do I push to remote?")),
    ("📥", _("How do I pull changes?")),
    ("↩️", _("How do I undo last commit?")),
    ("📜", _("How do I view commit history?")),
    ("🏷️", _("How do I create a tag?")),
    ("🔎", _("How do I find who changed a line?")),
    ("🗑️", _("How do I delete a branch?")),
    ("📋", _("How do I stash changes?")),
    # Docker Commands
    ("🐳", _("How do I list Docker containers?")),
    ("🚀", _("How do I run a Docker container?")),
    ("🛑", _("How do I stop a container?")),
    ("🖼️", _("How do I list Docker images?")),
    ("🧹", _("How do I clean Docker resources?")),
    ("📊", _("How do I view container logs?")),
    ("🔗", _("How do I create Docker network?")),
    ("💽", _("How do I manage Docker volumes?")),
    ("🏗️", _("How do I build a Docker image?")),
    ("🔄", _("How do I restart a container?")),
    # SSH and Networking
    ("🔑", _("How do I generate SSH keys?")),
    ("🔐", _("How do I copy SSH key to server?")),
    ("📡", _("How do I check open ports?")),
    ("🌐", _("How do I test network connectivity?")),
    ("🔍", _("How do I DNS lookup?")),
    ("📊", _("How do I monitor network traffic?")),
    ("🧱", _("How do I configure firewall?")),
    ("🔄", _("How do I create SSH tunnel?")),
    ("📋", _("How do I copy files via SSH?")),
    ("⚡", _("How do I speed up SSH connections?")),
    # File Operations
    ("📄", _("How do I create empty file?")),
    ("📂", _("How do I create directory?")),
    ("🗑️", _("How do I delete files safely?")),
    ("📋", _("How do I copy files?")),
    ("✂️", _("How do I move files?")),
    ("🔗", _("How do I create symbolic link?")),
    ("🔍", _("How do I search file contents?")),
    ("📊", _("How do I compare files?")),
    ("🔄", _("How do I sync directories?")),
    ("📝", _("How do I append to file?")),
    # Text Processing
    ("🔎", _("How do I use grep?")),
    ("✂️", _("How do I use awk?")),
    ("📝", _("How do I use sed?")),
    ("📊", _("How do I count lines?")),
    ("🔀", _("How do I sort text?")),
    ("🔗", _("How do I join files?")),
    ("🎯", _("How do I extract columns?")),
    ("🔄", _("How do I remove duplicates?")),
    ("📋", _("How do I format JSON?")),
    ("🔍", _("How do I search and replace?")),
    # System Administration
    ("👤", _("How do I add a user?")),
    ("👥", _("How do I manage groups?")),
    ("🔐", _("How do I change password?")),
    ("📊", _("How do I check system load?")),
    ("💽", _("How do I mount a drive?")),
    ("📦", _("How do I install packages?")),
    ("🔄", _("How do I update system?")),
    ("⚙️", _("How do I configure cron jobs?")),
    ("📜", _("How do I view system logs?")),
    ("🔍", _("How do I find large files?")),
    # Python Development
    ("🐍", _("How do I create virtualenv?")),
    ("📦", _("How do I install pip packages?")),
    ("🔍", _("How do I find Python package?")),
    ("📋", _("How do I list installed packages?")),
    ("🧪", _("How do I run Python tests?")),
    ("📊", _("How do I profile Python code?")),
    ("🔧", _("How do I format Python code?")),
    ("📝", _("How do I create requirements.txt?")),
    ("🚀", _("How do I run Python script?")),
    ("🔍", _("How do I debug Python?")),
    # Node.js Development
    ("📦", _("How do I initialize npm project?")),
    ("🔧", _("How do I install npm packages?")),
    ("🚀", _("How do I run npm scripts?")),
    ("📋", _("How do I list npm packages?")),
    ("🔄", _("How do I update npm packages?")),
    ("🧹", _("How do I clean npm cache?")),
    ("🔗", _("How do I link npm package?")),
    ("📊", _("How do I audit npm packages?")),
    ("🔍", _("How do I find npm package?")),
    ("⚡", _("How do I use npx?")),
    # Shell Scripting
    ("📝", _("How do I write a bash script?")),
    ("🔄", _("How do I use loops in bash?")),
    ("❓", _("How do I use conditionals?")),
    ("📊", _("How do I read user input?")),
    ("📁", _("How do I read from file?")),
    ("✍️", _("How do I write to file?")),
    ("🔧", _("How do I use functions?")),
    ("📋", _("How do I parse arguments?")),
    ("⚠️", _("How do I handle errors?")),
    ("🔍", _("How do I debug bash script?")),
    # Kubernetes
    ("☸️", _("How do I get pods?")),
    ("📊", _("How do I view pod logs?")),
    ("🚀", _("How do I deploy to k8s?")),
    ("🔄", _("How do I scale deployment?")),
    ("🔍", _("How do I describe pod?")),
    ("📋", _("How do I get services?")),
    ("⚙️", _("How do I create configmap?")),
    ("🔐", _("How do I create secret?")),
    ("🖥️", _("How do I exec into pod?")),
    ("📤", _("How do I port forward?")),
    # Database Operations
    ("🗄️", _("How do I connect to PostgreSQL?")),
    ("📊", _("How do I backup database?")),
    ("🔄", _("How do I restore database?")),
    ("📋", _("How do I list databases?")),
    ("🔍", _("How do I query from terminal?")),
    ("📤", _("How do I export to CSV?")),
    ("📥", _("How do I import from CSV?")),
    ("👤", _("How do I create database user?")),
    ("🔐", _("How do I grant permissions?")),
    ("📊", _("How do I check database size?")),
    # Performance and Monitoring
    ("📊", _("How do I monitor CPU usage?")),
    ("💾", _("How do I monitor memory?")),
    ("💽", _("How do I monitor disk I/O?")),
    ("🌐", _("How do I monitor network?")),
    ("⏱️", _("How do I benchmark command?")),
    ("🔍", _("How do I trace system calls?")),
    ("📈", _("How do I view process tree?")),
    ("🔥", _("How do I find bottlenecks?")),
    ("📋", _("How do I list open files?")),
    ("🧵", _("How do I view thread info?")),
    # Archives and Compression
    ("📦", _("How do I create tar archive?")),
    ("📂", _("How do I extract tar.gz?")),
    ("🗜️", _("How do I use gzip?")),
    ("📋", _("How do I list archive contents?")),
    ("➕", _("How do I add to archive?")),
    ("📤", _("How do I create zip file?")),
    ("📥", _("How do I extract zip?")),
    ("🔐", _("How do I encrypt archive?")),
    ("✂️", _("How do I split archive?")),
    ("🔗", _("How do I merge archives?")),
    # Security
    ("🔐", _("How do I encrypt file?")),
    ("🔓", _("How do I decrypt file?")),
    ("🔑", _("How do I generate password?")),
    ("✅", _("How do I verify checksum?")),
    ("📋", _("How do I list certificates?")),
    ("🔏", _("How do I sign file?")),
    ("🔍", _("How do I scan for vulnerabilities?")),
    ("🧹", _("How do I secure file permissions?")),
    ("📊", _("How do I audit system?")),
    ("🔐", _("How do I use GPG?")),
    # Tmux and Screen
    ("🖥️", _("How do I start tmux session?")),
    ("📋", _("How do I list tmux sessions?")),
    ("🔗", _("How do I attach to session?")),
    ("✂️", _("How do I split tmux pane?")),
    ("🔄", _("How do I switch panes?")),
    ("📝", _("How do I rename window?")),
    ("❌", _("How do I kill session?")),
    ("📤", _("How do I detach from session?")),
    ("📋", _("How do I copy in tmux?")),
    ("⚙️", _("How do I configure tmux?")),
    # Vim/Neovim
    ("📝", _("How do I save in vim?")),
    ("❌", _("How do I quit vim?")),
    ("🔍", _("How do I search in vim?")),
    ("🔄", _("How do I replace in vim?")),
    ("📋", _("How do I copy line in vim?")),
    ("✂️", _("How do I delete line in vim?")),
    ("↩️", _("How do I undo in vim?")),
    ("📊", _("How do I go to line in vim?")),
    ("🔀", _("How do I split in vim?")),
    ("📁", _("How do I open file in vim?")),
    # Environment and Config
    ("🔧", _("How do I set environment variable?")),
    ("📋", _("How do I list env variables?")),
    ("📝", _("How do I edit bashrc?")),
    ("🔄", _("How do I reload bashrc?")),
    ("📊", _("How do I view PATH?")),
    ("➕", _("How do I add to PATH?")),
    ("🔍", _("How do I find config file?")),
    ("📋", _("How do I export variable?")),
    ("🔐", _("How do I use .env file?")),
    ("⚙️", _("How do I set alias?")),
    # Advanced Commands
    ("🔗", _("How do I use xargs?")),
    ("📊", _("How do I use find with exec?")),
    ("🔄", _("How do I use parallel?")),
    ("📋", _("How do I use tee?")),
    ("⏱️", _("How do I use watch?")),
    ("📊", _("How do I use htop?")),
    ("🔍", _("How do I use fzf?")),
    ("📝", _("How do I use heredoc?")),
    ("🔄", _("How do I use subshell?")),
    ("📋", _("How do I use command substitution?")),
    # Misc
    ("📅", _("How do I format date?")),
    ("🧮", _("How do I calculate in terminal?")),
    ("🎨", _("How do I use colors in terminal?")),
    ("📊", _("How do I create histogram?")),
    ("🔔", _("How do I send notification?")),
    ("📋", _("How do I use clipboard?")),
    ("🖼️", _("How do I view image in terminal?")),
    ("📊", _("How do I plot in terminal?")),
    ("🔊", _("How do I play sound?")),
    ("⏰", _("How do I schedule task?")),
]


def get_random_quick_prompts(count: int = 6) -> list[tuple[str, str]]:
    """Get a random selection of quick prompts."""
    return random.sample(ALL_QUICK_PROMPTS, min(count, len(ALL_QUICK_PROMPTS)))
